### ISSUE TITLE
Truncated results

### ISSUE THREAD

**Issue by l4u84** [vahancho/polylineencoder#1]
when I try to decode a polyline I get coordinates with just 3/4 decimal. 
I don't get why the results are rounded up/truncated, how can I get a 5 decimal precision?

**Comment by vahancho** [comment]
Hi,
Could you please bring an example?

**Comment by l4u84** [comment]
sure,  I'll attach a file with the data.
[decodePolyline.txt](https://github.com/vahancho/polylineencoder/files/3022504/decodePolyline.txt)

**Comment by vahancho** [comment]
Thanks. And can you show how do you print the output values? It might be that the values are correct, but your serialization routine truncates them.

**Comment by l4u84** [comment]
sorry!!! you're right, the problem was with the output function. I was using std::cout and now with printf have no problem whatsoever so now I get the full results. 
Thank you!

**Comment by vahancho** [comment]
No problem. Thank you for your interest, anyways.
