### ISSUE TITLE
Left-shift of negative values undefined

### ISSUE THREAD

**Issue by shafiry** [vahancho/polylineencoder#15]
For line https://github.com/vahancho/polylineencoder/blob/master/src/polylineencoder.h#L181, is that defined behavior if the value is negative?

See https://stackoverflow.com/questions/8415895/is-left-and-right-shifting-negative-integers-defined-behavior

**Comment by vahancho** [comment]
Good point. Thank you. I will look into it.

**Comment by shafiry** [comment]
One option is to convert it to std::uint32_t

**Comment by vahancho** [comment]
The [algorithms ](https://developers.google.com/maps/documentation/utilities/polylinealgorithm)describes how to handle negative numbers.

> 3. Convert the decimal value to binary. Note that a negative value must be calculated using its [two's complement](https://en.wikipedia.org/wiki/Two%27s_complement) by inverting the binary value and adding one to the result:
> 00000001 00010010 10100001 11110001
> 11111110 11101101 01011110 00001110
> 11111110 11101101 01011110 00001111
