### ISSUE TITLE
namespace and version tag

### ISSUE THREAD

**Issue by wolfee001** [vahancho/polylineencoder#4]
Hi,

I'd like to create conan recipe for the lib. To be able to use it effectively in a professional environment, the lib should use a namespace. I would suggest 'polyline_encoder'.
To be able to create conan package for it, the lib needs a (usually semantic versioning) version tag. I would suggest 1.0.0

I would happily create the namespace change, but the version tag is on You.

Thanks

**Comment by vahancho** [comment]
I put the code into `gepaf` (_Google's Encoded Polyline Algorithm Format_) namespace. The version tag 1.0.0 has been created.

**Comment by wolfee001** [comment]
cool, thx
